[MINOR] add sign up service
Mauriciopizarro/black_jack pull request #31
Opened 2022-10-02 01:18 UTC by Mauriciopizarro

2022-10-02 02:50 UTC, Mauriciopizarro commented
@msotelo-eb i leave this pr for your code review.

2022-10-03 14:32 UTC, matisotee requested changes

2022-10-03 14:32 UTC, matisotee commented on controllers/sign_up_controller.py
> +from services.sign_up_service import SignUpService, EmptyPasswordError, UserExistent
If these exceptions are used in several controllers, I would create a new file called `exceptions.py` in the controllers folder that contains all the exceptions for the controllers layer

2022-10-03 14:32 UTC, matisotee commented on controllers/sign_up_controller.py
> +async def sign_up_controller(json_data: SignUpRequestData):
A better name for the first parameter would be `request` or `user`

2022-10-03 14:32 UTC, matisotee commented on controllers/sign_up_controller.py
> +    return {"User created succesfully"}
We should return a token and the user id

2022-10-03 14:32 UTC, matisotee commented on services/sign_up_service.py
> +        database.add({"username": username, "hashed_password": hashed_password})
All this code is responsibility of the repository

2022-10-03 20:45 UTC, merged